/*
 * Copyright (c) 2025, Adam G. Sweeney <agsweeney@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "webui.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "esp_err.h"
#include "sdkconfig.h"
#include <string.h>

static const char *TAG = "webui_html";

// Main page HTML
static const char index_page[] =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"<title>EtherNet/IP Scanner</title>"
"<style>"
"body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }"
".container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }"
"h1 { color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }"
".nav { margin-bottom: 20px; padding: 10px; background: #f9f9f9; border-radius: 5px; }"
".nav a { display: inline-block; margin-right: 15px; padding: 8px 15px; background-color: #4CAF50; color: white; text-decoration: none; border-radius: 4px; cursor: pointer; }"
".nav a:hover { background-color: #45a049; }"
".nav a.active, .nav span.active { background-color: #9e9e9e; cursor: default; pointer-events: none; opacity: 0.6; display: inline-block; margin-right: 15px; padding: 8px 15px; color: white; text-decoration: none; border-radius: 4px; }"
".section { margin: 20px 0; padding: 15px; background: #f9f9f9; border-radius: 5px; }"
"label { display: block; margin: 10px 0 5px 0; font-weight: bold; color: #555; }"
"input, textarea { width: 100%; padding: 8px; margin-bottom: 10px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; }"
"button { background-color: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; margin-right: 10px; }"
"button:hover { background-color: #45a049; }"
".error { color: #f44336; background: #ffebee; padding: 10px; border-radius: 4px; margin: 10px 0; }"
".success { color: #4CAF50; background: #e8f5e9; padding: 10px; border-radius: 4px; margin: 10px 0; }"
"textarea { font-family: monospace; }"
".hex-grid { display: grid; grid-template-columns: repeat(16, 1fr); gap: 2px; margin: 10px 0; }"
".hex-cell { background: #f0f0f0; border: 1px solid #ddd; padding: 4px 2px; text-align: center; font-family: monospace; font-size: 12px; cursor: pointer; min-width: 45px; }"
".hex-cell:hover { background: #e0e0e0; }"
".hex-cell input { width: 100%; min-width: 40px; border: none; background: transparent; text-align: center; font-family: monospace; font-size: 12px; padding: 2px; }"
".hex-cell input:focus { background: #fff; outline: 2px solid #4CAF50; width: 100%; }"
".hex-offset { font-family: monospace; font-size: 11px; color: #666; text-align: right; padding-right: 5px; min-width: 50px; }"
".hex-header { display: grid; grid-template-columns: 60px repeat(8, minmax(45px, 1fr)); gap: 2px; margin-bottom: 5px; }"
".hex-header-cell { text-align: center; font-size: 10px; color: #666; font-weight: bold; min-width: 45px; }"
".hex-row { display: grid; grid-template-columns: 60px repeat(8, minmax(45px, 1fr)); gap: 2px; margin-bottom: 2px; }"
"</style>"
"</head>"
"<body>"
"<div class=\"container\">"
"<h1>EtherNet/IP Scanner</h1>"
"<div class=\"nav\" id=\"mainNav\"></div>"
"<div class=\"section\">"
"<h2>Read/Write Assembly Data</h2>"
"<label for=\"writeIpAddress\">IP Address:</label>"
"<div style=\"display: flex; gap: 10px; align-items: center; margin-bottom: 10px;\">"
"<select id=\"writeIpAddressSelect\" onchange=\"updateIpAddress()\" style=\"flex: 1; max-width: 350px; padding: 8px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; display: none;\">"
"<option value=\"\">Select a device...</option>"
"</select>"
"<input type=\"text\" id=\"writeIpAddress\" placeholder=\"192.168.1.100\" value=\"\" style=\"flex: 1; max-width: 350px; padding: 8px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; display: block;\">"
"<button onclick=\"scanDevices()\" style=\"white-space: nowrap; padding: 8px 15px; flex-shrink: 0;\">Discover Devices</button>"
"</div>"
"<small style=\"color: #666; margin-top: -5px; margin-bottom: 15px; display: block;\">Click Discover Devices to scan the network, or enter IP address manually</small>"
"<label for=\"writeAssemblyInstance\">Assembly Instance:</label>"
"<div style=\"display: flex; gap: 10px; align-items: center; margin-bottom: 5px;\">"
"<select id=\"writeAssemblyInstanceSelect\" onchange=\"updateAssemblyInstance()\" style=\"flex: 0 0 200px; padding: 8px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; display: none;\">"
"<option value=\"\">Select an instance...</option>"
"</select>"
"<input type=\"number\" id=\"writeAssemblyInstance\" placeholder=\"Enter assembly instance number\" value=\"\" min=\"1\" max=\"65535\" style=\"flex: 0 0 200px; padding: 8px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box;\">"
"<button onclick=\"discoverAssemblies()\" style=\"white-space: nowrap; padding: 8px 15px; flex-shrink: 0;\">Discover</button>"
"</div>"
"<small style=\"color: #666; margin-top: -5px; margin-bottom: 15px; display: block;\">Click Discover to auto-detect instances, or enter manually</small>"
"<label for=\"writeTimeout\">Timeout (ms):</label>"
"<input type=\"number\" id=\"writeTimeout\" placeholder=\"5000\" value=\"5000\" min=\"1000\" max=\"30000\" style=\"max-width: 150px; width: 100%; padding: 8px; margin-bottom: 10px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box;\">"
"<button onclick=\"readAssemblyForWrite()\" style=\"margin-bottom: 15px;\">Read Assembly</button>"
"<div id=\"byteEditContainer\">"
"<label>Data (Decimal Editor - Click to edit, values 0-255):</label>"
"<div id=\"hexGrid\" style=\"background: #fff; padding: 10px; border: 1px solid #ddd; border-radius: 4px; max-height: 400px; overflow-y: auto;\"></div>"
"</div>"
"<button id=\"writeButton\" onclick=\"writeAssembly()\" style=\"margin-top: 10px; width: auto; min-width: 150px;\">Write Assembly</button>"
"<div id=\"writeResults\"></div>"
"</div>"
"</div>"
"<script>"
"document.addEventListener('DOMContentLoaded', function() {"
"  const nav = document.getElementById('mainNav');"
"  if (nav) {"
"    let navHtml = '<span class=\"active\">Assembly I/O</span>';"
#if CONFIG_ENIP_SCANNER_ENABLE_TAG_SUPPORT
"    navHtml += '<a href=\"/tags\">Tag Test</a>';"
#endif
"    nav.innerHTML = navHtml;"
"  }"
"});"
"function updateIpAddress() {"
"  const select = document.getElementById('writeIpAddressSelect');"
"  const input = document.getElementById('writeIpAddress');"
"  if (select.value) {"
"    input.value = select.value;"
"  }"
"}"
"function scanDevices() {"
"  const select = document.getElementById('writeIpAddressSelect');"
"  const input = document.getElementById('writeIpAddress');"
"  const resultsDiv = document.getElementById('writeResults');"
"  resultsDiv.innerHTML = '<p>Scanning for devices...</p>';"
"  fetch('/api/scanner/scan')"
"    .then(response => response.json())"
"    .then(data => {"
"      if (data.status === 'ok') {"
"        if (data.count === 0) {"
"          resultsDiv.innerHTML = '<div class=\"error\">No devices found</div>';"
"          select.style.display = 'none';"
"          input.style.display = 'block';"
"        } else {"
"          select.innerHTML = '<option value=\"\">Select a device...</option>';"
"          data.devices.forEach(device => {"
"            const option = document.createElement('option');"
"            option.value = device.ip_address;"
"            option.textContent = device.ip_address + ' - ' + (device.product_name || 'Unknown');"
"            select.appendChild(option);"
"          });"
"          select.style.display = 'block';"
"          input.style.display = 'none';"
"          resultsDiv.innerHTML = '<div class=\"success\">Found ' + data.count + ' device(s). Select from dropdown.</div>';"
"        }"
"      } else {"
"        resultsDiv.innerHTML = '<div class=\"error\">Scan failed</div>';"
"      }"
"    })"
"    .catch(error => {"
"      resultsDiv.innerHTML = '<div class=\"error\">Error: ' + error.message + '</div>';"
"    });"
"}"
"function updateAssemblyInstance() {"
"  const select = document.getElementById('writeAssemblyInstanceSelect');"
"  const input = document.getElementById('writeAssemblyInstance');"
"  if (select.value) {"
"    input.value = select.value;"
"  }"
"}"
"function discoverAssemblies() {"
"  const ipAddress = document.getElementById('writeIpAddress').value;"
"  const timeout = parseInt(document.getElementById('writeTimeout').value);"
"  const select = document.getElementById('writeAssemblyInstanceSelect');"
"  const input = document.getElementById('writeAssemblyInstance');"
"  const resultsDiv = document.getElementById('writeResults');"
"  if (!ipAddress) {"
"    resultsDiv.innerHTML = '<div class=\"error\">Please enter an IP address first</div>';"
"    return;"
"  }"
"  resultsDiv.innerHTML = '<p>Discovering assembly instances...</p>';"
"  fetch('/api/scanner/discover-assemblies', {"
"    method: 'POST',"
"    headers: { 'Content-Type': 'application/json' },"
"    body: JSON.stringify({"
"      ip_address: ipAddress,"
"      timeout_ms: timeout"
"    })"
"  })"
"    .then(response => response.json())"
"    .then(data => {"
"      if (data.status === 'ok' && data.count > 0) {"
"        select.innerHTML = '<option value=\"\">Select an instance...</option>';"
"        data.instances.forEach(instance => {"
"          const option = document.createElement('option');"
"          option.value = instance;"
"          option.textContent = 'Instance ' + instance;"
"          select.appendChild(option);"
"        });"
"        select.style.display = 'block';"
"        input.style.display = 'none';"
"        resultsDiv.innerHTML = '<div class=\"success\">Found ' + data.count + ' assembly instance(s). Select from dropdown.</div>';"
"      } else {"
"        select.style.display = 'none';"
"        input.style.display = 'block';"
"        resultsDiv.innerHTML = '<div class=\"error\">No assembly instances found. Please enter manually.</div>';"
"      }"
"    })"
"    .catch(error => {"
"      select.style.display = 'none';"
"      input.style.display = 'block';"
"      resultsDiv.innerHTML = '<div class=\"error\">Discovery failed: ' + error.message + '</div>';"
"    });"
"}"
"function readAssemblyForWrite() {"
"  const ipAddress = document.getElementById('writeIpAddress').value;"
"  const assemblyInstance = parseInt(document.getElementById('writeAssemblyInstance').value);"
"  const timeout = parseInt(document.getElementById('writeTimeout').value);"
"  const resultsDiv = document.getElementById('writeResults');"
"  if (!ipAddress) {"
"    resultsDiv.innerHTML = '<div class=\"error\">Please enter an IP address</div>';"
"    return;"
"  }"
"  if (!assemblyInstance || assemblyInstance < 1) {"
"    resultsDiv.innerHTML = '<div class=\"error\">Please enter a valid assembly instance</div>';"
"    return;"
"  }"
"  resultsDiv.innerHTML = '<p>Reading assembly data...</p>';"
"  fetch('/api/scanner/read-assembly', {"
"    method: 'POST',"
"    headers: { 'Content-Type': 'application/json' },"
"    body: JSON.stringify({"
"      ip_address: ipAddress,"
"      assembly_instance: assemblyInstance,"
"      timeout_ms: timeout"
"    })"
"  })"
"    .then(response => response.json())"
"    .then(data => {"
"      if (data.success) {"
"        resultsDiv.innerHTML = '<div class=\"success\">Assembly read successfully! Data loaded into form.</div>';"
"        populateWriteForm(data.data);"
"        checkWritable(ipAddress, assemblyInstance, timeout);"
"      } else {"
"        resultsDiv.innerHTML = '<div class=\"error\">Error: ' + (data.error || 'Unknown error') + '</div>';"
"      }"
"    })"
"    .catch(error => {"
"      resultsDiv.innerHTML = '<div class=\"error\">Error: ' + error.message + '</div>';"
"    });"
"}"
"function checkWritable(ipAddress, assemblyInstance, timeout) {"
"  fetch('/api/scanner/check-writable', {"
"    method: 'POST',"
"    headers: { 'Content-Type': 'application/json' },"
"    body: JSON.stringify({"
"      ip_address: ipAddress,"
"      assembly_instance: assemblyInstance,"
"      timeout_ms: timeout"
"    })"
"  })"
"    .then(response => response.json())"
"    .then(data => {"
"      const writeButton = document.getElementById('writeButton');"
"      if (data.writable) {"
"        writeButton.style.display = 'inline-block';"
"      } else {"
"        writeButton.style.display = 'none';"
"        const resultsDiv = document.getElementById('writeResults');"
"        resultsDiv.innerHTML = '<div class=\"error\">This assembly is not writable</div>';"
"      }"
"    })"
"    .catch(error => {"
"      console.error('Error checking writability:', error);"
"      document.getElementById('writeButton').style.display = 'inline-block';"
"    });"
"}"
"function populateWriteForm(data) {"
"  if (!data || data.length === 0) return;"
"  updateHexGrid(data);"
"}"
"function updateHexGrid(bytes) {"
"  const container = document.getElementById('hexGrid');"
"  container.innerHTML = '';"
"  if (!bytes || bytes.length === 0) return;"
"  container.dataset.originalLength = bytes.length.toString();"
"  const headerRow = document.createElement('div');"
"  headerRow.className = 'hex-header';"
"  headerRow.innerHTML = '<div class=\"hex-header-cell\">Offset</div>';"
"  for (let i = 0; i < 8; i++) {"
"    const headerCell = document.createElement('div');"
"    headerCell.className = 'hex-header-cell';"
"    headerCell.textContent = i.toString().padStart(3, '0');"
"    headerRow.appendChild(headerCell);"
"  }"
"  container.appendChild(headerRow);"
"  for (let row = 0; row < Math.ceil(bytes.length / 8); row++) {"
"    const rowDiv = document.createElement('div');"
"    rowDiv.className = 'hex-row';"
"    const offsetCell = document.createElement('div');"
"    offsetCell.className = 'hex-offset';"
"    offsetCell.textContent = (row * 8).toString().padStart(4, '0');"
"    rowDiv.appendChild(offsetCell);"
"    for (let col = 0; col < 8; col++) {"
"      const index = row * 8 + col;"
"      const cell = document.createElement('div');"
"      cell.className = 'hex-cell';"
"      const input = document.createElement('input');"
"      input.type = 'text';"
"      input.maxLength = 3;"
"      if (index < bytes.length) {"
"        input.value = bytes[index].toString();"
"      } else {"
"        input.disabled = true;"
"        input.style.background = '#f5f5f5';"
"        input.value = '';"
"      }"
"      input.dataset.index = index;"
"      input.oninput = function(e) {"
"        let val = this.value.replace(/[^0-9]/g, '');"
"        if (val.length > 3) {"
"          val = val.substring(0, 3);"
"        }"
"        this.value = val;"
"      };"
"      input.onblur = function() {"
"        if (this.value.length === 0) {"
"          this.value = '0';"
"        } else {"
"          const val = parseInt(this.value, 10);"
"          if (isNaN(val) || val < 0 || val > 255) {"
"            this.value = '0';"
"          } else {"
"            this.value = val.toString();"
"          }"
"        }"
"      };"
"      cell.appendChild(input);"
"      rowDiv.appendChild(cell);"
"    }"
"    container.appendChild(rowDiv);"
"  }"
"}"
"function getBytesFromHexGrid() {"
"  const container = document.getElementById('hexGrid');"
"  const originalLength = parseInt(container.dataset.originalLength || '0');"
"  if (originalLength === 0) return [];"
"  const inputs = document.querySelectorAll('#hexGrid input:not([disabled])');"
"  const bytes = [];"
"  for (let i = 0; i < originalLength && i < inputs.length; i++) {"
"    const val = parseInt(inputs[i].value, 10);"
"    if (!isNaN(val) && val >= 0 && val <= 255) {"
"      bytes.push(val);"
"    } else {"
"      bytes.push(0);"
"    }"
"  }"
"  return bytes;"
"}"
"function writeAssembly() {"
"  const ipAddress = document.getElementById('writeIpAddress').value;"
"  const assemblyInstance = parseInt(document.getElementById('writeAssemblyInstance').value);"
"  const timeout = parseInt(document.getElementById('writeTimeout').value);"
"  const resultsDiv = document.getElementById('writeResults');"
"  if (!ipAddress) {"
"    resultsDiv.innerHTML = '<div class=\"error\">Please enter an IP address</div>';"
"    return;"
"  }"
"  if (!assemblyInstance || assemblyInstance < 1) {"
"    resultsDiv.innerHTML = '<div class=\"error\">Please enter a valid assembly instance</div>';"
"    return;"
"  }"
"  let data = getBytesFromHexGrid();"
"  if (data.length === 0) {"
"    resultsDiv.innerHTML = '<div class=\"error\">Please read assembly data first or enter data in editor</div>';"
"    return;"
"  }"
"  if (data.length === 0) {"
"    resultsDiv.innerHTML = '<div class=\"error\">No data to write</div>';"
"    return;"
"  }"
"  resultsDiv.innerHTML = '<p>Writing assembly data...</p>';"
"  fetch('/api/scanner/write-assembly', {"
"    method: 'POST',"
"    headers: { 'Content-Type': 'application/json' },"
"    body: JSON.stringify({"
"      ip_address: ipAddress,"
"      assembly_instance: assemblyInstance,"
"      timeout_ms: timeout,"
"      data: data"
"    })"
"  })"
"    .then(response => response.json())"
"    .then(data => {"
"      if (data.success) {"
"        resultsDiv.innerHTML = '<div class=\"success\">Assembly written successfully!</div>';"
"      } else {"
"        resultsDiv.innerHTML = '<div class=\"error\">Error: ' + (data.error || 'Unknown error') + '</div>';"
"      }"
"    })"
"    .catch(error => {"
"      resultsDiv.innerHTML = '<div class=\"error\">Error: ' + error.message + '</div>';"
"    });"
"}"
"</script>"
"</body>"
"</html>";

// GET / - Serve Read/Write Assembly page
static esp_err_t webui_index_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");
    size_t html_len = strlen(index_page);
    ESP_LOGD(TAG, "Sending read/write page, length: %zu bytes", html_len);
    return httpd_resp_send(req, index_page, html_len);
}

#if CONFIG_ENIP_SCANNER_ENABLE_TAG_SUPPORT
// Tag test page HTML
static const char tags_page[] =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"<title>EtherNet/IP Tag Test</title>"
"<style>"
"body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }"
".container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }"
"h1 { color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }"
".nav { margin-bottom: 20px; padding: 10px; background: #f9f9f9; border-radius: 5px; }"
".nav a { display: inline-block; margin-right: 15px; padding: 8px 15px; background-color: #4CAF50; color: white; text-decoration: none; border-radius: 4px; }"
".nav a:hover { background-color: #45a049; }"
".section { margin: 20px 0; padding: 15px; background: #f9f9f9; border-radius: 5px; }"
"label { display: block; margin: 10px 0 5px 0; font-weight: bold; color: #555; }"
"input, select { width: 100%; padding: 8px; margin-bottom: 10px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; }"
"button { background-color: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; margin-right: 10px; }"
"button:hover { background-color: #45a049; }"
".error { color: #f44336; background: #ffebee; padding: 10px; border-radius: 4px; margin: 10px 0; }"
".success { color: #4CAF50; background: #e8f5e9; padding: 10px; border-radius: 4px; margin: 10px 0; }"
".info { color: #2196F3; background: #e3f2fd; padding: 10px; border-radius: 4px; margin: 10px 0; }"
"pre { background: #f5f5f5; padding: 10px; border-radius: 4px; overflow-x: auto; font-size: 12px; }"
".data-display { margin: 10px 0; padding: 10px; background: white; border: 1px solid #ddd; border-radius: 4px; }"
".data-row { margin: 5px 0; padding: 5px; border-bottom: 1px solid #eee; }"
".data-row:last-child { border-bottom: none; }"
"</style>"
"</head>"
"<body>"
"<div class=\"container\">"
"<h1>EtherNet/IP Tag Test</h1>"
"<div class=\"nav\">"
"<a href=\"/\">Assembly I/O</a>"
"<span class=\"active\">Tag Test</span>"
"</div>"
"<div class=\"info\" style=\"margin-bottom: 20px;\">"
"<strong>Note:</strong> This page is specifically designed for reading and writing tags on Allen-Bradley Micro800 series PLCs. <strong>This feature is experimental.</strong>"
"</div>"
"<div class=\"section\">"
"<h2>Read Tag</h2>"
"<label for=\"readIpAddress\">IP Address:</label>"
"<input type=\"text\" id=\"readIpAddress\" placeholder=\"192.168.1.100\" value=\"\">"
"<label for=\"readTagPath\">Tag Path:</label>"
"<input type=\"text\" id=\"readTagPath\" placeholder=\"MyTag\" value=\"\">"
"<small style=\"color: #666; display: block; margin-top: -5px; margin-bottom: 10px;\">Examples: MyTag, Program:MainProgram.Tag, MyArray[0]</small>"
"<label for=\"readTimeout\">Timeout (ms):</label>"
"<input type=\"number\" id=\"readTimeout\" placeholder=\"5000\" value=\"5000\" min=\"1000\" max=\"30000\" style=\"max-width: 150px;\">"
"<button onclick=\"readTag()\">Read Tag</button>"
"<div id=\"readResults\"></div>"
"</div>"
"<div class=\"section\">"
"<h2>Write Tag</h2>"
"<label for=\"writeIpAddress\">IP Address:</label>"
"<input type=\"text\" id=\"writeIpAddress\" placeholder=\"192.168.1.100\" value=\"\">"
"<label for=\"writeTagPath\">Tag Path:</label>"
"<input type=\"text\" id=\"writeTagPath\" placeholder=\"MyTag\" value=\"\">"
"<label for=\"writeDataType\">Data Type:</label>"
"<select id=\"writeDataType\">"
"<option value=\"193\">BOOL (1 byte)</option>"
"<option value=\"194\">SINT (1 byte)</option>"
"<option value=\"195\">INT (2 bytes)</option>"
"<option value=\"196\" selected>DINT (4 bytes)</option>"
"<option value=\"202\">REAL (4 bytes)</option>"
"<option value=\"218\">STRING (variable)</option>"
"</select>"
"<label for=\"writeValue\">Value:</label>"
"<input type=\"text\" id=\"writeValue\" placeholder=\"12345\" value=\"\">"
"<small style=\"color: #666; display: block; margin-top: -5px; margin-bottom: 10px;\">Enter numeric value (for BOOL: 0 or 1)</small>"
"<label for=\"writeTimeout\">Timeout (ms):</label>"
"<input type=\"number\" id=\"writeTimeout\" placeholder=\"5000\" value=\"5000\" min=\"1000\" max=\"30000\" style=\"max-width: 150px;\">"
"<button onclick=\"writeTag()\">Write Tag</button>"
"<div id=\"writeResults\"></div>"
"</div>"
"</div>"
"<script>"
"function readTag() {"
"  const ipAddress = document.getElementById('readIpAddress').value;"
"  const tagPath = document.getElementById('readTagPath').value;"
"  const timeout = parseInt(document.getElementById('readTimeout').value);"
"  const resultsDiv = document.getElementById('readResults');"
"  "
"  if (!ipAddress || !tagPath) {"
"    resultsDiv.innerHTML = '<div class=\"error\">Please enter IP address and tag path</div>';"
"    return;"
"  }"
"  "
"  resultsDiv.innerHTML = '<div class=\"info\">Reading tag...</div>';"
"  "
"  fetch('/api/scanner/read-tag', {"
"    method: 'POST',"
"    headers: { 'Content-Type': 'application/json' },"
"    body: JSON.stringify({"
"      ip_address: ipAddress,"
"      tag_path: tagPath,"
"      timeout_ms: timeout"
"    })"
"  })"
"  .then(response => response.json())"
"  .then(data => {"
"    if (data.success) {"
"      let html = '<div class=\"success\">Tag read successful!</div>';"
"      html += '<div class=\"data-display\">';"
"      html += '<div class=\"data-row\"><strong>Tag:</strong> ' + data.tag_path + '</div>';"
"      html += '<div class=\"data-row\"><strong>Data Type:</strong> ' + data.data_type_name + ' (0x' + data.cip_data_type.toString(16).toUpperCase() + ')</div>';"
"      html += '<div class=\"data-row\"><strong>Data Length:</strong> ' + data.data_length + ' bytes</div>';"
"      html += '<div class=\"data-row\"><strong>Response Time:</strong> ' + data.response_time_ms + ' ms</div>';"
"      "
"      if (data.value_bool !== undefined) {"
"        html += '<div class=\"data-row\"><strong>Value (BOOL):</strong> ' + data.value_bool + '</div>';"
"      } else if (data.value_sint !== undefined) {"
"        html += '<div class=\"data-row\"><strong>Value (SINT):</strong> ' + data.value_sint + '</div>';"
"      } else if (data.value_int !== undefined) {"
"        html += '<div class=\"data-row\"><strong>Value (INT):</strong> ' + data.value_int + '</div>';"
"      } else if (data.value_dint !== undefined) {"
"        html += '<div class=\"data-row\"><strong>Value (DINT):</strong> ' + data.value_dint + '</div>';"
"      } else if (data.value_real !== undefined) {"
"        html += '<div class=\"data-row\"><strong>Value (REAL):</strong> ' + data.value_real + '</div>';"
"      }"
"      "
"      if (data.data_hex) {"
"        html += '<div class=\"data-row\"><strong>Hex:</strong> ' + data.data_hex + '</div>';"
"      }"
"      "
"      if (data.data && data.data.length > 0) {"
"        html += '<div class=\"data-row\"><strong>Raw Bytes:</strong> [' + data.data.join(', ') + ']</div>';"
"      }"
"      "
"      html += '</div>';"
"      resultsDiv.innerHTML = html;"
"    } else {"
"      resultsDiv.innerHTML = '<div class=\"error\">Read failed: ' + (data.error || 'Unknown error') + '</div>';"
"    }"
"  })"
"  .catch(error => {"
"    resultsDiv.innerHTML = '<div class=\"error\">Error: ' + error.message + '</div>';"
"  });"
"}"
""
"function writeTag() {"
"  const ipAddress = document.getElementById('writeIpAddress').value;"
"  const tagPath = document.getElementById('writeTagPath').value;"
"  const dataType = parseInt(document.getElementById('writeDataType').value);"
"  const value = document.getElementById('writeValue').value;"
"  const timeout = parseInt(document.getElementById('writeTimeout').value);"
"  const resultsDiv = document.getElementById('writeResults');"
"  "
"  if (!ipAddress || !tagPath || !value) {"
"    resultsDiv.innerHTML = '<div class=\"error\">Please enter IP address, tag path, and value</div>';"
"    return;"
"  }"
"  "
"  // Convert value to bytes based on data type"
"  let dataArray = [];"
"  try {"
"    if (dataType == 193) { // BOOL"
"      const boolVal = parseInt(value) ? 1 : 0;"
"      dataArray = [boolVal];"
"    } else if (dataType == 194) { // SINT"
"      const sintVal = parseInt(value);"
"      dataArray = [sintVal & 0xFF];"
"    } else if (dataType == 195) { // INT"
"      const intVal = parseInt(value);"
"      dataArray = [intVal & 0xFF, (intVal >> 8) & 0xFF];"
"    } else if (dataType == 196) { // DINT"
"      const dintVal = parseInt(value);"
"      dataArray = [dintVal & 0xFF, (dintVal >> 8) & 0xFF, (dintVal >> 16) & 0xFF, (dintVal >> 24) & 0xFF];"
"    } else if (dataType == 202) { // REAL"
"      const realVal = parseFloat(value);"
"      const buffer = new ArrayBuffer(4);"
"      const view = new DataView(buffer);"
"      view.setFloat32(0, realVal, true); // little-endian"
"      for (let i = 0; i < 4; i++) {"
"        dataArray.push(view.getUint8(i));"
"      }"
"    } else {"
"      resultsDiv.innerHTML = '<div class=\"error\">Unsupported data type for write</div>';"
"      return;"
"    }"
"  } catch (e) {"
"    resultsDiv.innerHTML = '<div class=\"error\">Invalid value: ' + e.message + '</div>';"
"    return;"
"  }"
"  "
"  resultsDiv.innerHTML = '<div class=\"info\">Writing tag...</div>';"
"  "
"  fetch('/api/scanner/write-tag', {"
"    method: 'POST',"
"    headers: { 'Content-Type': 'application/json' },"
"    body: JSON.stringify({"
"      ip_address: ipAddress,"
"      tag_path: tagPath,"
"      cip_data_type: dataType,"
"      data: dataArray,"
"      timeout_ms: timeout"
"    })"
"  })"
"  .then(response => response.json())"
"  .then(data => {"
"    if (data.success) {"
"      resultsDiv.innerHTML = '<div class=\"success\">Tag write successful!</div>';"
"    } else {"
"      resultsDiv.innerHTML = '<div class=\"error\">Write failed: ' + (data.error || 'Unknown error') + '</div>';"
"    }"
"  })"
"  .catch(error => {"
"    resultsDiv.innerHTML = '<div class=\"error\">Error: ' + error.message + '</div>';"
"  });"
"}"
"</script>"
"</body>"
"</html>";

// GET /tags - Serve Tag Test page
static esp_err_t webui_tags_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");
    size_t html_len = strlen(tags_page);
    ESP_LOGD(TAG, "Sending tags page, length: %zu bytes", html_len);
    return httpd_resp_send(req, tags_page, html_len);
}
#endif

// Register HTML page handlers
esp_err_t webui_html_register(httpd_handle_t server)
{
    httpd_uri_t index_uri = {
        .uri = "/",
        .method = HTTP_GET,
        .handler = webui_index_handler,
        .user_ctx = NULL
    };
    httpd_register_uri_handler(server, &index_uri);
    
    // Also register /write for backwards compatibility
    httpd_uri_t write_uri = {
        .uri = "/write",
        .method = HTTP_GET,
        .handler = webui_index_handler,
        .user_ctx = NULL
    };
    httpd_register_uri_handler(server, &write_uri);
    
    ESP_LOGI(TAG, "Web UI HTML pages registered (/, /write)");
#if CONFIG_ENIP_SCANNER_ENABLE_TAG_SUPPORT
    httpd_uri_t tags_uri = {
        .uri = "/tags",
        .method = HTTP_GET,
        .handler = webui_tags_handler,
        .user_ctx = NULL
    };
    httpd_register_uri_handler(server, &tags_uri);
    ESP_LOGI(TAG, "Tag test page registered (/tags)");
#endif
    return ESP_OK;
}
